// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_bestTime = new UnifiedLeaderboard("BestTime",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "grp.best.time"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI5bGF2oADEAIQAA"
#else
            "BestTime"
#endif
            );

        public static UnifiedLeaderboard BestTime
        {
            get { return s_bestTime; }
        }

        private static readonly UnifiedLeaderboard s_levelProgress = new UnifiedLeaderboard("LevelProgress",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "grp.level.progress"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI5bGF2oADEAIQAQ"
#else
            "LevelProgress"
#endif
            );

        public static UnifiedLeaderboard LevelProgress
        {
            get { return s_levelProgress; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "BestTime", s_bestTime },
            { "LevelProgress", s_levelProgress }
        };
    }
}
